### ISSUE TITLE
[Feature Request] Adjust width of split view

### ISSUE THREAD

**Issue by mbfakourii** [Cierra-Runis/based_widget#1]
In a program like Telegram, it is possible to enlarge and reduce two pages. Please add this feature in this great package.

Two examples of videos in the Telegram program :

![2024-02-03_21-51-30](https://raw.githubusercontent.com/mbfakourii/mbfakouri.ir/master/2024-02-03_21-51-30.gif)

![2024-02-03_21-59-35](https://raw.githubusercontent.com/mbfakourii/mbfakouri.ir/master/2024-02-03_21-59-35.gif)

**Comment by Cierra-Runis** [comment]
Enjoy it😘

**Comment by Cierra-Runis** [comment]
It's not perfect tought. Telegram does better, when the window is resized after the width is adjusted to half, telegram will scale the two views roughly in half, but based_split_view is fixed.

**Comment by mbfakourii** [comment]
> Enjoy it😘

Thanks ❤️❤️

> It's not perfect tought. Telegram does better, when the window is resized after the width is adjusted to half, telegram will scale the two views roughly in half, but based_split_view is fixed.

Do you mean the small left screen?

![image](https://github.com/Cierra-Runis/based_widget/assets/29329988/7ada5122-9d54-426f-a3a2-4161072d8f2d)

**Comment by Cierra-Runis** [comment]
Example as below:

![image](https://github.com/Cierra-Runis/based_widget/assets/29329988/6e78427e-eb86-4c55-a5da-910453cebe86)

Telegram’s way of handling split view is obviously better. You can also compare the logical differences between them.

**Comment by Cierra-Runis** [comment]
Nothing. If you have other questions, please open another issue💖
